---
- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    force_apt_get: yes

- name: add grafana gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: install grafana
  apt:
    name: grafana
    state: present
    force_apt_get: yes

- name: enabled and start grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started
    daemon_reload: yes
